POST {{baseUrl}}/base/user/login
Content-Type: application/json

{"username": "admin", "password": "123456"}

###
POST {{baseUrl}}/base/user/list
Content-Type: application/json

{"name": "ad","page": 1, "pageSize": 20}

###
