POST {{baseUrl}}/base/user/login
Content-Type: application/json

{"username": "admin", "password": "111111"}

###
POST {{baseUrl}}/base/user/list
Content-Type: application/json

{"page": 1, "pageSize": 20}

###
